"""Print / regenerate the tool catalogue.

    python scripts/tools_catalogue.py              # grouped list, one line each
    python scripts/tools_catalogue.py -v           # full descriptions + args
    python scripts/tools_catalogue.py NAME         # detail for tools matching NAME
    python scripts/tools_catalogue.py --write      # regenerate TOOLS.md

Grouping is derived, not hand-maintained: each module is registered into its own
throwaway MCPServer and the resulting tool names are the group. So a tool added
to a module shows up here with no edit to this file, and a tool that silently
fails to register is visibly absent.
"""

from __future__ import annotations

import argparse
import asyncio
import os
import sys

sys.path.insert(0, os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "src"))

from mcp.server import MCPServer  # noqa: E402

from mobileagent.tools import (device_tools, explore_tools, input_tools,  # noqa: E402
                               registry_tools, system_tools, thread_tools,
                               ui_tools)
from mobileagent.tools.apps import instagram as ig_tools  # noqa: E402
from mobileagent.tools.apps import instagram_comments as ig_comments  # noqa: E402
from mobileagent.tools.apps import instagram_profile as ig_profile  # noqa: E402
from mobileagent.tools.apps import instagram_web as ig_web  # noqa: E402
from mobileagent.tools.apps import reel_capture as ig_capture  # noqa: E402
from mobileagent.tools.apps import twitter as x_tools  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# (label, [registrar callables]) - mirrors server.py wiring.
GROUPS = [
    ("Device & connection",   [device_tools.register]),
    ("Screen reading",        [ui_tools.register]),
    ("Input",                 [input_tools.register]),
    ("System / phone",        [system_tools.register]),
    ("Agent learning",        [explore_tools.register]),
    ("Threads & comments",    [thread_tools.register]),
    ("Selector registry",     [registry_tools.register]),
    ("Instagram - core",      [ig_tools.register]),
    ("Instagram - profile",   [ig_profile.register,
                               ig_profile.register_orchestrator,
                               ig_profile.register_about]),
    ("Instagram - comments",  [ig_comments.register]),
    ("Instagram - capture",   [ig_capture.register, ig_capture.register_full]),
    ("Instagram - web/loader", [ig_web.register, ig_web.register_session_import]),
    ("X / Twitter",           [x_tools.register, x_tools.register_nav,
                               x_tools.register_timelines]),
]


async def collect():
    """-> [(group, [Tool, ...])], plus any tool the real server has that no
    group claims (which would mean server.py and this file have diverged)."""
    out, claimed = [], set()
    for label, registrars in GROUPS:
        probe = MCPServer(name="probe")
        for reg in registrars:
            reg(probe)
        tools = sorted(await probe.list_tools(), key=lambda t: t.name)
        out.append((label, tools))
        claimed.update(t.name for t in tools)

    from mobileagent.server import mcp as real
    actual = {t.name for t in await real.list_tools()}
    return out, sorted(actual - claimed), sorted(claimed - actual)


def first_line(desc: str) -> str:
    return (desc or "").strip().split("\n")[0].strip()


def arg_summary(tool) -> str:
    schema = tool.input_schema or {}
    props, req = schema.get("properties", {}), set(schema.get("required", []))
    if not props:
        return "()"
    parts = [p if p in req else f"{p}?" for p in props]
    return "(" + ", ".join(parts) + ")"


def render_text(groups, verbose, needle):
    total = 0
    for label, tools in groups:
        shown = [t for t in tools if not needle or needle.lower() in t.name.lower()]
        if not shown:
            continue
        print(f"\n=== {label} ({len(shown)}) ===")
        for t in shown:
            total += 1
            if verbose or needle:
                print(f"\n  {t.name}{arg_summary(t)}")
                for line in (t.description or "").strip().split("\n"):
                    print(f"      {line}")
            else:
                print(f"  {t.name:<26} {first_line(t.description)[:74]}")
    print(f"\n{total} tools")


def render_md(groups, orphans, missing) -> str:
    lines = [
        "# Tool catalogue",
        "",
        "Generated by `python scripts/tools_catalogue.py --write` - do not edit "
        "by hand.",
        "",
        "An MCP client receives all of this automatically at handshake; this "
        "file exists so a human can browse the surface without starting a "
        "session.",
        "",
    ]
    n = sum(len(t) for _, t in groups)
    lines += [f"**{n} tools** across {len(groups)} groups.", ""]
    if orphans:
        lines += ["> **Warning:** registered on the server but in no group here: "
                  + ", ".join(f"`{o}`" for o in orphans), ""]
    if missing:
        lines += ["> **Warning:** grouped here but NOT on the server: "
                  + ", ".join(f"`{m}`" for m in missing), ""]
    for label, tools in groups:
        lines += [f"## {label}", "", "| Tool | Arguments | Description |",
                  "|---|---|---|"]
        for t in tools:
            desc = first_line(t.description).replace("|", "\\|")
            args = arg_summary(t).replace("|", "\\|")
            lines.append(f"| `{t.name}` | `{args}` | {desc} |")
        lines.append("")
    lines += ["---", "",
              "`?` marks an optional argument. Descriptions are the first line "
              "only; the full text is what the agent actually receives."]
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("needle", nargs="?", help="only tools whose name matches")
    ap.add_argument("-v", "--verbose", action="store_true")
    ap.add_argument("--write", action="store_true", help="regenerate TOOLS.md")
    a = ap.parse_args()

    groups, orphans, missing = asyncio.run(collect())
    if a.write:
        path = os.path.join(ROOT, "TOOLS.md")
        with open(path, "w", encoding="utf-8") as f:
            f.write(render_md(groups, orphans, missing))
        print(f"wrote {path} ({sum(len(t) for _, t in groups)} tools)")
        if orphans:
            print("  WARNING ungrouped:", ", ".join(orphans))
        if missing:
            print("  WARNING not on server:", ", ".join(missing))
        return
    render_text(groups, a.verbose, a.needle)
    if orphans:
        print("WARNING ungrouped:", ", ".join(orphans))
    if missing:
        print("WARNING not on server:", ", ".join(missing))


if __name__ == "__main__":
    main()
